// Auto-generated by @thexjs/core -- do not edit
export type RouteMap = {
  "/": Record<string, never>;
  "/features": Record<string, never>;
  "/docs": Record<string, never>;
  "/docs/secret-redaction": Record<string, never>;
  "/docs/content-collections": Record<string, never>;
  "/docs/isr": Record<string, never>;
  "/docs/build-deploy": Record<string, never>;
  "/docs/request-tracing": Record<string, never>;
  "/docs/backpressure": Record<string, never>;
  "/docs/tutorial": Record<string, never>;
  "/docs/configuration": Record<string, never>;
  "/docs/observability": Record<string, never>;
  "/docs/data-layer": Record<string, never>;
  "/docs/server-functions": Record<string, never>;
  "/docs/layouts": Record<string, never>;
  "/docs/api-routes": Record<string, never>;
  "/docs/routing": Record<string, never>;
  "/docs/installation": Record<string, never>;
  "/docs/islands": Record<string, never>;
  "/docs/packages/auth": Record<string, never>;
  "/docs/packages/hooks": Record<string, never>;
  "/docs/packages/cli": Record<string, never>;
  "/docs/packages/env": Record<string, never>;
  "/docs/packages/adapter-vercel": Record<string, never>;
  "/docs/packages/mcp": Record<string, never>;
  "/docs/packages/core": Record<string, never>;
  "/docs/migration": Record<string, never>;
  "/docs/client-navigation": Record<string, never>;
  "/docs/pages": Record<string, never>;
  "/docs/introduction": Record<string, never>;
  "/docs/audit-trail": Record<string, never>;
  "/docs/security": Record<string, never>;
  "/docs/getting-started": Record<string, never>;
  "/docs/middleware": Record<string, never>;
  "/sandbox": Record<string, never>;
};

export function href<T extends keyof RouteMap & string>(
  path: T,
  ...[params]: RouteMap[T] extends Record<string, never> ? [] : [RouteMap[T]]
): string {
  if (!params) return path;
  let result: string = path;
  for (const [key, value] of Object.entries(params)) {
    result = result.replace(new RegExp(`:${key}(?=/|$)`), encodeURIComponent(String(value)));
  }
  // Catch-all params have no `:name` token in the path — they render as an
  // anonymous `*` segment. Substitute them in segment order, keeping `/`
  // between encoded fragments so multi-segment values stay readable. An exact
  // segment-token check (prefixed by `/`) is required: a prefix scan of
  // `:key` would also match a longer `:id2` param and skip the wildcard.
  const isNamedToken = (key: string) => new RegExp(`(^|/):${key}(?=/|$)`).test(path);
  for (const [key, value] of Object.entries(params)) {
    if (!isNamedToken(key)) {
      const encoded = String(value)
        .split("/")
        .map(encodeURIComponent)
        .join("/");
      result = result.replace(/\*/, encoded);
    }
  }
  result = result.replace(/\*+$/, "");
  return result;
}
