// Auto-generated by @thexjs/core -- do not edit
export type RouteMap = {
  "/": Record<string, never>;
  "/features": Record<string, never>;
  "/docs": Record<string, never>;
  "/docs/content-collections": Record<string, never>;
  "/docs/build-deploy": Record<string, never>;
  "/docs/configuration": Record<string, never>;
  "/docs/observability": Record<string, never>;
  "/docs/data-layer": Record<string, never>;
  "/docs/server-functions": Record<string, never>;
  "/docs/layouts": Record<string, never>;
  "/docs/api-routes": Record<string, never>;
  "/docs/routing": Record<string, never>;
  "/docs/installation": Record<string, never>;
  "/docs/packages/cli": Record<string, never>;
  "/docs/packages/env": Record<string, never>;
  "/docs/packages/adapter-vercel": Record<string, never>;
  "/docs/packages/core": Record<string, never>;
  "/docs/client-navigation": Record<string, never>;
  "/docs/pages": Record<string, never>;
  "/docs/introduction": Record<string, never>;
  "/docs/security": Record<string, never>;
  "/docs/getting-started": Record<string, never>;
  "/docs/middleware": Record<string, never>;
  "/play": Record<string, never>;
};

export function href<T extends keyof RouteMap & string>(
  path: T,
  ...[params]: RouteMap[T] extends Record<string, never> ? [] : [RouteMap[T]]
): string {
  if (!params) return path;
  let result: string = path;
  for (const [key, value] of Object.entries(params)) {
    result = result.replace(new RegExp(`:${key}(?=/|$)`), encodeURIComponent(String(value)));
  }
  result = result.replace(/\*+$/, "");
  return result;
}
