// Auto-generated by @x/core -- do not edit
export type RouteMap = {
  "/": Record<string, never>;
  "/blog": Record<string, never>;
  "/blog/:slug": { slug: string };
  "/about": Record<string, never>;
};

export function href<T extends keyof RouteMap & string>(
  path: T,
  ...[params]: RouteMap[T] extends Record<string, never> ? [] : [RouteMap[T]]
): string {
  if (!params) return path;
  let result: string = path;
  for (const [key, value] of Object.entries(params)) {
    result = result.replace(new RegExp(`:${key}(?=/|$)`), encodeURIComponent(String(value)));
  }
  result = result.replace(/\*+$/, "");
  return result;
}
