import { readdirSync, statSync, writeFileSync } from "node:fs";
import { join, relative, sep } from "node:path";

export interface RouteEntry {
  filePath: string;
  routePath: string;
  paramNames: string[];
  isApi: boolean;
}

export interface MiddlewareEntry {
  filePath: string;
  dirPath: string;
}

const ROUTE_FILE = /\.(tsx|ts)$/;

export function scanRoutes(rootDir: string): RouteEntry[] {
  const entries: RouteEntry[] = [];

  function walk(dir: string) {
    for (const name of readdirSync(dir)) {
      if (name.startsWith("_") || name.startsWith(".")) continue;

      const full = join(dir, name);
      const stat = statSync(full);

      if (stat.isDirectory()) {
        walk(full);
        continue;
      }

      if (!ROUTE_FILE.test(name)) continue;

      const rel = relative(rootDir, full).replace(ROUTE_FILE, "");
      entries.push(toRouteEntry(rel, full));
    }
  }

  walk(rootDir);
  return entries;
}

function toRouteEntry(relPath: string, filePath: string): RouteEntry {
  const segments = relPath.split(sep);
  const paramNames: string[] = [];
  const isApi = segments[0] === "api";

  const routeSegments = segments.map((segment) => {
    if (segment === "index") return "";
    if (segment.startsWith("[...") && segment.endsWith("]")) {
      const name = segment.slice(4, -1);
      paramNames.push(name);
      return "*";
    }
    if (segment.startsWith("[") && segment.endsWith("]")) {
      const name = segment.slice(1, -1);
      paramNames.push(name);
      return `:${name}`;
    }
    return segment;
  });

  const joined = routeSegments.filter((s) => s.length > 0).join("/");
  const routePath = joined.length === 0 ? "/" : `/${joined}`;

  return { filePath, routePath, paramNames, isApi };
}

export interface LayoutEntry {
  filePath: string;
  dirPath: string;
}

export function scanLayouts(rootDir: string): LayoutEntry[] {
  const entries: LayoutEntry[] = [];

  function walk(dir: string) {
    for (const name of readdirSync(dir)) {
      if (name.startsWith(".")) continue;
      const full = join(dir, name);
      const stat = statSync(full);

      if (stat.isDirectory()) {
        walk(full);
      } else if (name === "_layout.tsx" || name === "_layout.ts") {
        entries.push({ filePath: full, dirPath: dir });
      }
    }
  }

  walk(rootDir);
  return entries;
}

export function findLayoutChain(
  routeFilePath: string,
  layouts: LayoutEntry[],
  routesDir: string,
): LayoutEntry[] {
  const routeDir = join(routeFilePath, "..");
  const chain: LayoutEntry[] = [];

  let current = routeDir;
  while (current.startsWith(routesDir)) {
    const layout = layouts.find((l) => l.dirPath === current);
    if (layout) chain.unshift(layout);
    const parent = join(current, "..");
    if (parent === current) break;
    current = parent;
  }

  return chain;
}

export function scanMiddleware(rootDir: string): MiddlewareEntry[] {
  const entries: MiddlewareEntry[] = [];

  function walk(dir: string) {
    for (const name of readdirSync(dir)) {
      if (name.startsWith(".")) continue;
      const full = join(dir, name);
      const stat = statSync(full);

      if (stat.isDirectory()) {
        walk(full);
      } else if (name === "_middleware.ts" || name === "_middleware.tsx") {
        entries.push({ filePath: full, dirPath: dir });
      }
    }
  }

  walk(rootDir);
  return entries;
}

export function findMiddlewareChain(
  routeFilePath: string,
  middleware: MiddlewareEntry[],
  routesDir: string,
): MiddlewareEntry[] {
  const routeDir = join(routeFilePath, "..");
  const chain: MiddlewareEntry[] = [];

  let current = routeDir;
  while (current.startsWith(routesDir)) {
    const mw = middleware.find((m) => m.dirPath === current);
    if (mw) chain.unshift(mw);
    const parent = join(current, "..");
    if (parent === current) break;
    current = parent;
  }

  return chain;
}

export function routePatternToRegex(routePath: string): RegExp {
  const regexStr = routePath
    .replace(/\//g, "\\/")
    .replace(/:(\w+)/g, "([^/]+)")
    .replace(/\*/g, "(.+)");

  return new RegExp(`^${regexStr}$`);
}

export function extractParams(
  routePath: string,
  paramNames: string[],
  url: string,
): Record<string, string> | null {
  const regex = routePatternToRegex(routePath);
  const match = url.match(regex);
  if (!match) return null;

  const params: Record<string, string> = {};
  let idx = 1;
  for (const name of paramNames) {
    const value = match[idx];
    if (value !== undefined) {
      params[name] = value;
    }
    idx++;
  }
  return params;
}

export function generateManifestSource(routes: RouteEntry[]): string {
  const routeEntries = routes.map((r) => {
    const paramsType =
      r.paramNames.length === 0
        ? "Record<string, never>"
        : `{ ${r.paramNames.map((n) => `${n}: string`).join("; ")} }`;
    return `  "${r.routePath}": ${paramsType};`;
  });

  return `// Auto-generated by @x/core -- do not edit
export type RouteMap = {
${routeEntries.join("\n")}
};

export function href<T extends keyof RouteMap & string>(
  path: T,
  ...[params]: RouteMap[T] extends Record<string, never> ? [] : [RouteMap[T]]
): string {
  if (!params) return path;
  let result: string = path;
  for (const [key, value] of Object.entries(params)) {
    result = result.replace(new RegExp(\`:\${key}(?=/|$)\`), encodeURIComponent(String(value)));
  }
  result = result.replace(/\\*+$/, "");
  return result;
}
`;
}

export function writeManifest(routes: RouteEntry[], routesDir: string): string {
  const source = generateManifestSource(routes);
  const manifestPath = join(routesDir, "..", "x-routes.ts");
  writeFileSync(manifestPath, source, "utf-8");
  return manifestPath;
}
