import { relative } from "node:path";
import type { BuildManifest, CompiledModuleRef } from "./types";

function importPath(from: string, ref: CompiledModuleRef): string {
  let rel = relative(from, ref.compiledPath).replaceAll("\\", "/");
  if (!rel.startsWith(".")) rel = `./${rel}`;
  return rel;
}

/**
 * Emits the source for `entry.mjs`: the actual render function.
 *
 * Every route/layout/middleware/action module is imported *statically* (no
 * `import(pathVariable)` anywhere) so the bundler in bundle.ts can trace and
 * inline the whole dependency graph -- including `@thexjs/core`,
 * `react-dom/server`, etc -- into one standalone file, which is what
 * `.vc-config.json`'s `nodejs20.x` runtime expects to run.
 */
export function generateEntrySource(manifest: BuildManifest, entryDir: string): string {
  const lines: string[] = [];

  lines.push(
    '// Auto-generated by @thexjs/adapter-vercel -- do not edit.',
    'import { createElement } from "react";',
    "import {",
    "  composeMiddleware,",
    "  renderPage,",
    "  renderStreamingPage,",
    "  DefaultNotFound,",
    "  registerServerFunctions,",
    "  getServerFunctionHandler,",
    '} from "@thexjs/core";',
    "",
  );

  // -- static imports, one identifier per unique source file --------------
  const refs = new Map<string, CompiledModuleRef>();
  const collect = (ref: CompiledModuleRef) => refs.set(ref.identifier, ref);
  for (const r of manifest.routes) {
    collect(r.route);
    for (const l of r.layoutChain) collect(l);
    for (const m of r.middlewareChain) collect(m);
  }
  for (const a of manifest.actions) collect(a.module);
  if (manifest.notFound) collect(manifest.notFound);
  if (manifest.rootLayout) collect(manifest.rootLayout);

  for (const ref of refs.values()) {
    lines.push(`import * as ${ref.identifier} from "${importPath(entryDir, ref)}";`);
  }
  lines.push("");

  // -- register standalone server actions (actionsDir) at cold start ------
  for (const a of manifest.actions) {
    lines.push(
      `{`,
      `  const mod = ${a.module.identifier};`,
      `  const parentPath = ${JSON.stringify(a.parentPath)};`,
      `  const paramNames = ${JSON.stringify(a.paramNames)};`,
      `  if (mod.actions) registerServerFunctions(parentPath, paramNames, mod.actions);`,
      `  for (const [key, value] of Object.entries(mod)) {`,
      `    if (key === "default" || key === "actions" || typeof value !== "function") continue;`,
      `    registerServerFunctions(parentPath, paramNames, { [key]: value });`,
      `  }`,
      `}`,
    );
  }
  lines.push("");

  // -- route table ----------------------------------------------------------
  lines.push("const ROUTES = [");
  for (const r of manifest.routes) {
    lines.push(
      "  {",
      `    routePath: ${JSON.stringify(r.routePath)},`,
      `    paramNames: ${JSON.stringify(r.paramNames)},`,
      `    isApi: ${r.isApi},`,
      `    mod: ${r.route.identifier},`,
      `    layoutModules: [${r.layoutChain.map((l) => `${l.identifier}.default`).join(", ")}].filter(Boolean),`,
      `    middlewareModules: [${r.middlewareChain
        .map((m) => `${m.identifier}.middleware`)
        .join(", ")}].filter(Boolean),`,
      "  },",
    );
  }
  lines.push("];");
  lines.push("");

  lines.push(
    `const notFoundComponent = ${manifest.notFound ? `${manifest.notFound.identifier}.default ?? DefaultNotFound` : "DefaultNotFound"};`,
    `const notFoundLayout = ${manifest.rootLayout ? `${manifest.rootLayout.identifier}.default` : "undefined"};`,
    "",
  );

  // -- shared helpers (mirrors @thexjs/core internals; kept local so we
  //    don't need to export path-matching internals from core) -----------
  lines.push(
    `const HTTP_METHODS = ["GET", "POST", "PUT", "PATCH", "DELETE"];`,
    "",
    "function routePatternToRegex(routePath) {",
    "  const regexStr = routePath",
    '    .replace(/[.*+?^${}()|[\\]\\\\]/g, "\\\\$&")',
    '    .replace(/\\\\\\*/g, "(.+)")',
    '    .replace(/:(\\w+)/g, "([^/]+)");',
    '  return new RegExp("^" + regexStr + "$");',
    "}",
    "",
    "function extractParams(routePath, paramNames, url) {",
    "  const regex = routePatternToRegex(routePath);",
    "  const match = url.match(regex);",
    "  if (!match) return null;",
    "  const params = {};",
    "  let idx = 1;",
    "  for (const name of paramNames) {",
    "    if (match[idx] !== undefined) params[name] = match[idx];",
    "    idx++;",
    "  }",
    "  return params;",
    "}",
    "",
    "function wrapWithLayouts(Component, params, loaderData, layoutModules) {",
    "  let content = createElement(Component, { params, loaderData });",
    "  for (const Layout of [...layoutModules].reverse()) {",
    "    content = createElement(Layout, null, content);",
    "  }",
    "  return content;",
    "}",
    "",
    "function renderNotFound() {",
    "  const content = notFoundLayout",
    "    ? createElement(notFoundLayout, null, createElement(notFoundComponent, { params: {} }))",
    "    : createElement(notFoundComponent, { params: {} });",
    '  const html = renderPage(content, { title: "404 — Not Found" });',
    '  return new Response(html, { status: 404, headers: { "Content-Type": "text/html; charset=utf-8" } });',
    "}",
    "",
    "const serverFnHandler = getServerFunctionHandler();",
    "",
  );

  // -- request dispatcher ---------------------------------------------------
  lines.push(
    "export async function handleRequest(request) {",
    "  const url = new URL(request.url).pathname;",
    "",
    "  const actionResult = await serverFnHandler(request);",
    "  if (actionResult !== null) return actionResult;",
    "",
    "  for (const route of ROUTES) {",
    "    const params = extractParams(route.routePath, route.paramNames, url);",
    "    if (params === null) continue;",
    "",
    "    if (route.isApi) {",
    "      const method = request.method;",
    "      const handlerFn = route.mod[method];",
    "      if (typeof handlerFn !== \"function\") {",
    '        return new Response(`Method ${method} not allowed`, { status: 405 });',
    "      }",
    "      try {",
    "        const result = await handlerFn(request);",
    "        if (result instanceof Response) return result;",
    '        if (result === undefined || result === null) return new Response("OK", { status: 200 });',
    "        return Response.json(result);",
    "      } catch (err) {",
    '        console.error("[x/vercel] API handler error:", err);',
    '        return new Response("Internal server error", { status: 500 });',
    "      }",
    "    }",
    "",
    "    const Component = route.mod.default;",
    "    if (!Component) continue;",
    "",
    "    const baseHandler = async (ctx) => {",
    "      let loaderData = {};",
    "      const loader = route.mod.loader;",
    "      if (loader) {",
    "        const result = await loader(ctx);",
    "        if (result instanceof Response) return result;",
    "        loaderData = result;",
    "      }",
    "      const content = wrapWithLayouts(Component, ctx.params, loaderData, route.layoutModules);",
    "      const stream = await renderStreamingPage(content, {});",
    '      return new Response(stream, { headers: { "Content-Type": "text/html; charset=utf-8" } });',
    "    };",
    "",
    "    try {",
    "      if (route.middlewareModules.length > 0) {",
    "        const composed = composeMiddleware(route.middlewareModules, baseHandler);",
    '        return await composed({ params, request }, async () => new Response("Not found", { status: 404 }));',
    "      }",
    "      return await baseHandler({ params, request });",
    "    } catch (err) {",
    '      console.error("[x/vercel] route handler error:", err);',
    '      return new Response("Internal server error", { status: 500 });',
    "    }",
    "  }",
    "",
    "  return renderNotFound();",
    "}",
    "",
  );

  // -- Node <-> Web Request/Response bridge (Vercel `nodejs*.x` runtime
  //    functions are invoked Node-style: `(req, res) => void`) -------------
  lines.push(
    "function nodeRequestToWebRequest(req) {",
    '  const protocol = req.headers["x-forwarded-proto"] || "https";',
    '  const host = req.headers["x-forwarded-host"] || req.headers.host || "localhost";',
    "  const url = `${protocol}://${host}${req.url}`;",
    "  const headers = new Headers();",
    "  for (const [key, value] of Object.entries(req.headers)) {",
    "    if (value === undefined) continue;",
    "    if (Array.isArray(value)) { for (const v of value) headers.append(key, v); }",
    "    else headers.append(key, value);",
    "  }",
    '  const hasBody = req.method !== "GET" && req.method !== "HEAD";',
    "  return new Request(url, {",
    "    method: req.method,",
    "    headers,",
    "    body: hasBody ? req : undefined,",
    "    duplex: hasBody ? \"half\" : undefined,",
    "  });",
    "}",
    "",
    "async function sendWebResponse(response, res) {",
    "  res.statusCode = response.status;",
    "  for (const [key, value] of response.headers) {",
    '    if (key.toLowerCase() === "set-cookie") continue;',
    "    res.setHeader(key, value);",
    "  }",
    "  const cookies = response.headers.getSetCookie ? response.headers.getSetCookie() : [];",
    '  if (cookies.length > 0) res.setHeader("Set-Cookie", cookies);',
    "  if (!response.body) { res.end(); return; }",
    "  const reader = response.body.getReader();",
    "  while (true) {",
    "    const { done, value } = await reader.read();",
    "    if (done) break;",
    "    res.write(value);",
    "  }",
    "  res.end();",
    "}",
    "",
    "export default async function handler(req, res) {",
    "  try {",
    "    const request = nodeRequestToWebRequest(req);",
    "    const response = await handleRequest(request);",
    "    await sendWebResponse(response, res);",
    "  } catch (err) {",
    '    console.error("[x/vercel] fatal error handling request:", err);',
    "    res.statusCode = 500;",
    '    res.end("Internal server error");',
    "  }",
    "}",
  );

  return lines.join("\n");
}
