import { relative } from "node:path";
import type { BuildManifest, CompiledModuleRef } from "./types";

function importPath(from: string, ref: CompiledModuleRef): string {
  let rel = relative(from, ref.compiledPath).replaceAll("\\", "/");
  if (!rel.startsWith(".")) rel = `./${rel}`;
  return rel;
}

/**
 * Emits the source for `entry.mjs`: the actual render function.
 *
 * Every route/layout/middleware/action module is imported *statically* (no
 * `import(pathVariable)` anywhere) so the bundler in bundle.ts can trace and
 * inline the whole dependency graph -- including `@thexjs/core`,
 * `react-dom/server`, etc -- into one standalone file, which is what
 * `.vc-config.json`'s `nodejs20.x` runtime expects to run.
 *
 * The request pipeline is not reimplemented here: the entry builds a real
 * `createApp()` from `@thexjs/core` (with a pre-resolved route manifest so
 * no filesystem scanning or dynamic `.tsx` import happens at request time)
 * and delegates every request to `app.fetch()`. That means the deployed
 * function behaves exactly like the `x start` production server -- health
 * checks, rate limiting, revalidation, server actions, the /_x/image proxy,
 * SSR with loaders/layouts/middleware, API routes, security headers, the 404
 * page, request logging -- all of it, with no drift between the two.
 */
export function generateEntrySource(manifest: BuildManifest, entryDir: string): string {
  const lines: string[] = [];

  lines.push(
    "// Auto-generated by @thexjs/adapter-vercel -- do not edit.",
    'import { createApp, registerServerFunctions } from "@thexjs/core";',
    "",
  );

  // -- security & observability config --------------------------------------
  const securityOpts = JSON.stringify(manifest.security ?? {});
  const observabilityOpts = JSON.stringify(manifest.observability ?? {});
  const imagesOpts = JSON.stringify(manifest.images ?? {});
  lines.push(
    `const __x_security = ${securityOpts};`,
    `const __x_observability = ${observabilityOpts};`,
    `const __x_images = ${imagesOpts};`,
    "",
  );

  // -- static imports, one identifier per unique source file --------------
  const refs = new Map<string, CompiledModuleRef>();
  const collect = (ref: CompiledModuleRef) => refs.set(ref.identifier, ref);
  for (const r of manifest.routes) {
    collect(r.route);
    for (const l of r.layoutChain) collect(l);
    for (const m of r.middlewareChain) collect(m);
  }
  for (const a of manifest.actions) collect(a.module);
  if (manifest.notFound) collect(manifest.notFound);
  if (manifest.rootLayout) collect(manifest.rootLayout);

  for (const ref of refs.values()) {
    lines.push(`import * as ${ref.identifier} from "${importPath(entryDir, ref)}";`);
  }
  lines.push("");

  // -- register standalone server actions (actionsDir) at cold start ------
  for (const a of manifest.actions) {
    lines.push(
      "{",
      `  const mod = ${a.module.identifier};`,
      `  const parentPath = ${JSON.stringify(a.parentPath)};`,
      `  const paramNames = ${JSON.stringify(a.paramNames)};`,
      "  if (mod.actions) registerServerFunctions(parentPath, paramNames, mod.actions);",
      "  for (const [key, value] of Object.entries(mod)) {",
      `    if (key === "default" || key === "actions" || typeof value !== "function") continue;`,
      "    registerServerFunctions(parentPath, paramNames, { [key]: value });",
      "  }",
      "}",
    );
  }
  lines.push("");

  // -- preloaded route manifest ----------------------------------------------
  lines.push("const __x_preloadedRoutes = [");
  for (const r of manifest.routes) {
    const entryObj = {
      routePath: r.routePath,
      paramNames: r.paramNames,
      isApi: r.isApi,
      filePath: r.route.sourcePath,
    };
    const layoutMods = r.layoutChain.map((l) => `${l.identifier}.default`).join(", ");
    const mwMods = r.middlewareChain.map((m) => `${m.identifier}.middleware`).join(", ");
    lines.push(
      "  {",
      `    entry: ${JSON.stringify(entryObj)},`,
      `    mode: ${JSON.stringify(r.mode)},`,
      ...(r.revalidate !== undefined ? [`    revalidate: ${r.revalidate},`] : []),
      `    module: ${r.route.identifier},`,
      `    layoutModules: [${layoutMods}].filter(Boolean),`,
      `    middlewareModules: [${mwMods}].filter(Boolean),`,
      // Server-mode pages can't re-bundle islands at request time on Vercel
      // (Bun-only), so pin an empty list -- islands on server-mode pages are
      // a future pre-bundled-at-build-time enhancement. Static pages already
      // ship their island <script> tags baked into the prerendered HTML.
      "    islandScripts: [],",
      "  },",
    );
  }
  lines.push("];");
  lines.push("");

  // -- build the real app (same pipeline as `x start`) -----------------------
  lines.push(
    "const __x_app = await createApp({",
    `  pagesDir: ${JSON.stringify(manifest.pagesDirLabel)},`,
    "  development: false,",
    "  port: parseInt(process.env.PORT || '3000', 10),",
    ...(manifest.stylesheetHref
      ? [`  stylesheetHref: ${JSON.stringify(manifest.stylesheetHref)},`]
      : []),
    "  ...(Object.keys(__x_security).length > 0 ? { security: __x_security } : {}),",
    "  ...(Object.keys(__x_observability).length > 0 ? { observability: __x_observability } : {}),",
    "  ...(Object.keys(__x_images).length > 0 ? { images: __x_images } : {}),",
    "  preloaded: {",
    "    routes: __x_preloadedRoutes,",
    ...(manifest.notFound
      ? [`    notFoundComponent: ${manifest.notFound.identifier}.default ?? undefined,`]
      : []),
    ...(manifest.rootLayout
      ? [`    notFoundLayout: ${manifest.rootLayout.identifier}.default ?? undefined,`]
      : []),
    "  },",
    "});",
    "",
  );

  // -- Node <-> Web Request/Response bridge (Vercel `nodejs*.x` runtime
  //    functions are invoked Node-style: `(req, res) => void`) -------------
  lines.push(
    "function nodeRequestToWebRequest(req) {",
    '  const protocol = req.headers["x-forwarded-proto"] || "https";',
    '  const host = req.headers["x-forwarded-host"] || req.headers.host || "localhost";',
    "  const url = `${protocol}://${host}${req.url}`;",
    "  const headers = new Headers();",
    "  for (const [key, value] of Object.entries(req.headers)) {",
    "    if (value === undefined) continue;",
    "    if (Array.isArray(value)) { for (const v of value) headers.append(key, v); }",
    "    else headers.append(key, value);",
    "  }",
    '  const hasBody = req.method !== "GET" && req.method !== "HEAD";',
    "  return new Request(url, {",
    "    method: req.method,",
    "    headers,",
    "    body: hasBody ? req : undefined,",
    '    duplex: hasBody ? "half" : undefined,',
    "  });",
    "}",
    "",
    "async function sendWebResponse(response, res) {",
    "  res.statusCode = response.status;",
    "  for (const [key, value] of response.headers) {",
    '    if (key.toLowerCase() === "set-cookie") continue;',
    "    res.setHeader(key, value);",
    "  }",
    "  const cookies = response.headers.getSetCookie ? response.headers.getSetCookie() : [];",
    '  if (cookies.length > 0) res.setHeader("Set-Cookie", cookies);',
    "  if (!response.body) { res.end(); return; }",
    "  const reader = response.body.getReader();",
    "  while (true) {",
    "    const { done, value } = await reader.read();",
    "    if (done) break;",
    "    res.write(value);",
    "  }",
    "  res.end();",
    "}",
    "",
    "export default async function handler(req, res) {",
    "  try {",
    "    const request = nodeRequestToWebRequest(req);",
    "    const response = await __x_app.fetch(request);",
    "    await sendWebResponse(response, res);",
    "  } catch (err) {",
    "    console.error('[x] fatal error handling request:', err);",
    "    res.statusCode = 500;",
    '    res.end("Internal server error");',
    "  }",
    "}",
  );

  return lines.join("\n");
}
